export enum GameAction {
  BUY = 'BUY',
  BUY_VILLAGERS = 'BUY_VILLAGERS',
  SELL_FOOD = 'SELL_FOOD',
  SELL_MATERIALS = 'SELL_MATERIALS',
  SELL_RELICS = 'SELL_RELICS',
  INVADE = 'INVADE',
  EXTRACT = 'EXTRACT',
  REINFORCE = 'REINFORCE',
  UPGRADE = 'UPGRADE',
  PRESTIGE = 'PRESTIGE',
}
