export enum Unit {
  WARRIOR = 'WARRIOR',
  ARCHER = 'ARCHER',
  MAGE = 'MAGE',
  HEALER = 'HEALER',
  TANK = 'TANK',
  ROGUE = 'ROGUE',
  NECROMANCER = 'NECROMANCER',
  DRACO_METAMORPH = 'DRACO_METAMORPH',
}
