spring:
  application:
    name: tower-dungeon
  output:
    ansi:
      enabled: always

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

server:
  compression:
    enabled: true
  http2:
    enabled: true
  port: 8080
